services:

  selenium-hub:
    image: selenium/hub:4.18.1
    container_name: selenium-hub

    ports:
      - "4444:4444"

  chrome1:
    image: selenium/node-chrome:4.18.1
    container_name: chrome1

    shm_size: 2gb

    depends_on:
      - selenium-hub

    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1

  chrome2:
    image: selenium/node-chrome:4.18.1
    container_name: chrome2

    shm_size: 2gb

    depends_on:
      - selenium-hub

    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1

  chrome3:
    image: selenium/node-chrome:4.18.1
    container_name: chrome3

    shm_size: 2gb

    depends_on:
      - selenium-hub

    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1